{{- if .Values.agent.enabled -}}
{{- if .Values.agent.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "harvester-vm-dhcp-controller.agentServiceAccountName" . }}
  labels:
    {{- include "harvester-vm-dhcp-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
  {{- with .Values.agent.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
