---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    {}
  name: virtualmachinenetworkconfigs.network.harvesterhci.io
spec:
  group: network.harvesterhci.io
  names:
    kind: VirtualMachineNetworkConfig
    listKind: VirtualMachineNetworkConfigList
    plural: virtualmachinenetworkconfigs
    shortNames:
    - vmnetcfg
    - vmnetcfgs
    singular: virtualmachinenetworkconfig
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.vmName
      name: VMNAME
      type: string
    - jsonPath: .status.conditions[?(@.type=='Allocated')].status
      name: ALLOCATED
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: AGE
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            properties:
              networkConfig:
                items:
                  properties:
                    ipAddress:
                      type: string
                    macAddress:
                      type: string
                    networkName:
                      type: string
                  type: object
                type: array
              paused:
                type: boolean
              vmName:
                type: string
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      type: string
                    lastUpdateTime:
                      description: The last time this condition was updated.
                      type: string
                    message:
                      description: Human-readable message indicating details about
                        last transition
                      type: string
                    reason:
                      description: The reason for the condition's last transition.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of cluster condition.
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              networkConfig:
                items:
                  properties:
                    allocatedIPAddress:
                      type: string
                    macAddress:
                      type: string
                    networkName:
                      type: string
                    state:
                      type: string
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources: {}
