#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

echo "Packaging webhook..."

# Build container images
IMAGE=${REPO}/vm-dhcp-webhook:${TAG}
DOCKERFILE=package/Dockerfile.webhook

buildx build --load \
  --build-arg http_proxy="${http_proxy}" \
  --build-arg https_proxy="${https_proxy}" \
  --build-arg no_proxy="${no_proxy}" \
  -f ${DOCKERFILE} -t ${IMAGE} .
echo Built ${IMAGE}

# Image push (if specified)
IMAGE_PUSH=${REPO}/harvester-vm-dhcp-webhook:${IMAGE_PUSH_TAG}
docker tag "${IMAGE}" "${IMAGE_PUSH}"
echo Tagged "${IMAGE_PUSH}"

DOCKER_CONFIG=".docker"
if [[ -n ${PUSH} ]];then
  docker --config=${DOCKER_CONFIG} push "${IMAGE_PUSH}"
  echo Pushed "${IMAGE_PUSH}"
fi

