#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

echo "Packaging..."

# Copy out artifacts
mkdir -p dist/artifacts
cp bin/vm-dhcp-agent dist/artifacts/vm-dhcp-agent${SUFFIX}

# Build container images
IMAGE=${REPO}/vm-dhcp-agent:${TAG}
DOCKERFILE=package/Dockerfile.agent

docker build -f ${DOCKERFILE} -t ${IMAGE} .
echo Built ${IMAGE}

# Image push (if specified)
IMAGE_PUSH=${REPO}/harvester-vm-dhcp-agent:${IMAGE_PUSH_TAG}
docker tag "${IMAGE}" "${IMAGE_PUSH}"
echo Tagged "${IMAGE_PUSH}"

DOCKER_CONFIG=".docker"
if [[ -n ${PUSH} ]];then
  docker --config=${DOCKER_CONFIG} push "${IMAGE_PUSH}"
  echo Pushed "${IMAGE_PUSH}"
fi
