# syntax=docker/dockerfile:1.18.0

FROM registry.suse.com/bci/bci-base:15.7

RUN zypper -n rm container-suseconnect && \
    zypper -n in curl

ARG TARGETPLATFORM

RUN if [ "$TARGETPLATFORM" != "linux/amd64" ] && [ "$TARGETPLATFORM" != "linux/arm64" ]; then \
    echo "Error: Unsupported TARGETPLATFORM: $TARGETPLATFORM" && \
    exit 1; \
    fi

ENV ARCH=${TARGETPLATFORM#linux/}

COPY bin/vm-dhcp-webhook-${ARCH} /usr/bin/vm-dhcp-webhook

ENTRYPOINT [ "vm-dhcp-webhook" ]
